name: wc

on:
  push:
    branches: [ "*" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: golangci/golangci-lint-action@v6
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Install  
      run: go mod download
    - name: Lint
      run: make lint
    - name: Tests
      run: make test
